// Ajax request actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// User actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

// Exposed items actions
export const RETRIEVE_EXPOSED_ITEMS_SUCCESS = 'RETRIEVE_EXPOSED_ITEMS_SUCCESS';
export const START_EXPOSED_ITEM_SUCCESS = 'START_EXPOSED_ITEM_SUCCESS';

// Task actions
export const RESET_TASK_SEARCH = 'RESET_TASK_SEARCH';
export const SEARCH_TASKS_SUCCESS = 'SEARCH_TASKS_SUCCESS';

// Process instances actions
export const RESET_PROCESS_INSTANCE_SEARCH = 'RESET_PROCESS_INSTANCE_SEARCH';
export const SEARCH_PROCESS_INSTANCES_SUCCESS = 'SEARCH_PROCESS_INSTANCES_SUCCESS';

// Process instance actions
export const RESET_PROCESS_INSTANCE = 'RESET_PROCESS_INSTANCE';
export const STORE_IS_PROCESS_INSTANCE_PRELOADED_FROM_PARENT = 'STORE_IS_PROCESS_INSTANCE_PRELOADED_FROM_PARENT';
export const RETRIEVE_PROCESS_INSTANCE_SUMMARY_SUCCESS = 'RETRIEVE_PROCESS_INSTANCE_SUMMARY_SUCCESS';
export const RETRIEVE_PROCESS_INSTANCE_BUSINESS_DATA_SUCCESS = 'RETRIEVE_PROCESS_INSTANCE_BUSINESS_DATA_SUCCESS';
export const RETRIEVE_PROCESS_INSTANCE_TASKS_SUCCESS = 'RETRIEVE_PROCESS_INSTANCE_TASKS_SUCCESS';
export const RETRIEVE_PROCESS_INSTANCE_ACTIVITIES_SUCCESS = 'RETRIEVE_PROCESS_INSTANCE_ACTIVITIES_SUCCESS';
